version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: pwd
      - run: ls
      - run: echo "text to output here" > output.txt
      - run: ls
      - persist_to_workspace:
          root: .
          paths: 
            - output.txt
  
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - run: pwd
      - run: ls
      - run: cat ../output.txt
      - attach_workspace:
          at: .

workflows:
  workspace-demo:
    jobs: 
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output


