version: 2.1

docker-def: &docker-def
    docker:
      - image: circleci/node:13.8.0

jobs:
  save_hello_world_output:
    <<: *docker-def
    # docker:
    #   - image: circleci/node:13.8.0
    steps:
      - run: pwd
      - run: ls
      - run: echo "text to output here" > ~/output.txt
      - run: ls
      - persist_to_workspace:
          root: ~/
          paths: 
            - output.txt
  
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt


workflows:
  workspace-demo:
    jobs: 
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output


